version: 2

models:
  - name: mart_customer_360
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: mart_rfm_segments
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: r_score
        tests:
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5]
      - name: segment
        tests:
          - accepted_values:
              arguments:
                values: ["champions", "loyal", "at_risk", "hibernating", "new", "standard"]